BENCHMARK:
  NB201PATH: ./data/NAS-Bench-201-v1_1-096897.pth
  NB301PATH: ./data/nb301models/
CUDNN_BENCH: true
DARTS:
  ALPHA_LR: 0.0003
  ALPHA_WEIGHT_DECAY: 0.001
  UNROLLED: true
DETERMINSTIC: true
EVAL_PERIOD: 1
LOADER:
  BATCH_SIZE: 64
  DATAPATH: ''
  DATASET: cifar10
  NUM_CLASSES: 10
  NUM_WORKERS: 8
  PIN_MEMORY: true
  SPLIT:
  - 0.5
  - 0.5
  USE_VAL: false
LOG_PERIOD: 10
NUM_GPUS: 1
OPTIM:
  BASE_LR: 0.1
  DAMPENING: 0.0
  FINAL_EPOCH: 0
  GRAD_CLIP: 5.0
  LR_MULT: 0.1
  LR_POLICY: cos
  MAX_EPOCH: 50
  MIN_LR: 0.001
  MOMENTUM: 0.9
  NESTEROV: false
  STEPS:
  - 30
  - 60
  - 90
  WARMUP_EPOCH: 0
  WARMUP_FACTOR: 0.1
  WEIGHT_DECAY: 0.0005
OUT_DIR: exp/search/darts_darts_cifar10
RNG_SEED: 1
SAVE_PERIOD: 1
SEARCH:
  AUTO_RESUME: true
  EVALUATION: ''
  IM_SIZE: 32
  INPUT_CHANNELS: 3
  LABEL_SMOOTH: 0.0
  LOSS_FUN: cross_entropy
  MULTI_SIZES: []
  WEIGHTS: ''
SPACE:
  BASIC_OP: []
  CHANNELS: 16
  LAYERS: 8
  NAME: darts
  NODES: 4
TEST:
  BATCH_SIZE: 128
  IM_SIZE: 224
TRAIN:
  CHANNELS: 36
  DROP_PATH_PROB: 0.2
  GENOTYPE: ''
  IM_SIZE: 32
  INPUT_CHANNELS: 3
  LAYERS: 20
